name: Block Autosquash Commits

on: pull_request

jobs:
  block-autosquash-commits:
    name: Block Autosquash Commits
    runs-on: ubuntu-latest
    steps:
      - name: Block Autosquash Commits
        uses: xt0rted/block-autosquash-commits-action@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
